library(shiny)
library(foreign)
library(plyr)
library(ggplot2)
library(scales)
#remove all previous loaded data
rm(list=ls())
# The name of the state codes used in 2015 data
states2015a<-list(
  "Alabama"="1",
  "Alska"="2",
  "Arizona"="4",
  "Arkansas"="5",
  "California"="6",
  "Colorado"="8",
  "Connecticut"="9",
  "Delaware"="10",
  "District of Columbia"="11",
  "Florida"="12",
  "Goergia"="13",
  "Hawaii"="15",
  "Idaho"="16",
  "Illinois"="17",
  "Indiana"="18",
  "Iowa"="19",
  "Kansas"="20",
  "Kentucky"="21",
  "Louisiana"="22",
  "Maine"="23",
  "Maryland"="24",
  "Massachussests"="25",
  "Michigan"="26",
  "Minnesota"="27",
  "Missisipi"="28",
  "Missouri"="29",
  "Montana"="30",
  "Nebraska"="31",
  "Nevada"="32",
  "New Hampshire"="33",
  "New Jersey"="34",
  "New Mexico"="35",
  "New York"="36",
  "North Carolina"="37",
  "North Dakota"="38",
  "Ohio"="39",
  "Oklahoma"="40",
  "Oregon"="41",
  "Pennsylvania"="42",
  "Puerto Rico"="43",
  "Rhode Island"="44",
  "South Carolina"="45",
  "South Dakota"="46",
  "Tennessee"="47",
  "Texas"="48",
  "Utah"="49",
  "Vermont"="50",
  "Virginia"="51",
  "Virgin Islands"="52",
  "Washington"="53",
  "West Virginia"="54",
  "Wisconsin"="55",
  "Wyoming"="56"
)

states2015b<-list(
  "1"="Alabama",
  "2"="Alska",
  "4"="Arizona",
  "5"="Arkansas",
  "6"="California",
  "8"="Colorado",
  "9"="Connecticut",
  "10"="Delaware",
  "11"="District of Columbia",
  "12"="Florida",
  "13"="Goergia",
  "15"="Hawaii",
  "16"="Idaho",
  "17"="Illinois",
  "18"="Indiana",
  "19"="Iowa",
  "20"="Kansas",
  "21"="Kentucky",
  "22"="Louisiana",
  "23"="Maine",
  "24"="Maryland",
  "25"="Massachussests",
  "26"="Michigan",
  "27"="Minnesota",
  "28"="Missisipi",
  "29"="Missouri",
  "30"="Montana",
  "31"="Nebraska",
  "32"="Nevada",
  "33"="New Hampshire",
  "34"="New Jersey",
  "35"="New Mexico",
  "36"="New York",
  "37"="North Carolina",
  "38"="North Dakota",
  "39"="Ohio",
  "40"="Oklahoma",
  "41"="Oregon",
  "42"="Pennsylvania",
  "43"="Puerto Rico",
  "44"="Rhode Island",
  "45"="South Carolina",
  "46"="South Dakota",
  "47"="Tennessee",
  "48"="Texas",
  "49"="Utah",
  "50"="Vermont",
  "51"="Virginia",
  "52"="Virgin Islands",
  "53"="Washington",
  "54"="West Virginia",
  "55"="Wisconsin",
  "56"="Wyoming"
)
accidentQuestionList=list("States according to drunk drive?"="1"
)

week_days<-list("1"="Sunday","2"="Monday","3"="Tuesday","4"="Wednesday","5"="Thursday","6"="Friday","7"="Saturday")
months<-list(
  "1"="January",
  "2"="February",
  "3"="March",
  "4"="April",
  "5"="May",
  "6"="June",
  "7"="July",
  "8"="August",
  "9"="Septemeber",
  "10"="October",
  "11"="November",
  "12"="December"
)

statesCode <- c("1","2","4","5","6","8","9","10","11","12","13","15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56")

accidentdatag <- read.dbf("../data/2004/FARS2004/accident.dbf")

